// Catálogos iniciales de las listas desplegables. Se siembran una sola vez; luego el
// Administrador los edita desde la aplicación. `codigo` es un identificador estable usado por las
// reglas de negocio (no editable).

export const categorias = [
  ['SEXO', 'Sexo'],
  ['PROCEDENCIA', 'Procedencia'],
  ['MUNICIPIOS', 'Municipios de Nariño'],
  ['EPS', 'EPS'],
  ['DIAGNOSTICO', 'Diagnóstico'],
  ['VALVULOPATIA', 'Tipo de valvulopatía'],
  ['RIESGOS', 'Factores de riesgo'],
  ['RACHS', 'Escala RACHS-1'],
  ['PROCEDIMIENTOS', 'Procedimientos quirúrgicos'],
  ['IMPLANTE', 'Tipo de implante'],
  ['COMPLICACION_INTRAQX', 'Complicación intraquirúrgica'],
  ['UNIDAD_POP', 'Unidad postoperatoria'],
  ['COMPLICACION_POP', 'Complicación postoperatoria'],
  ['CONDICION_SALIDA', 'Condición de salida'],
  ['ESTADO_HERIDA', 'Estado de la herida quirúrgica'],
  ['CAUSA_REINGRESO', 'Causa de reingreso'],
]

export const opciones = {
  SEXO: [
    { codigo: null, valor: "Femenino", orden: 10 },
    { codigo: null, valor: "Masculino", orden: 20 },
    { codigo: null, valor: "Otro", orden: 30 },
  ],
  PROCEDENCIA: [
    { codigo: 'NARINO', valor: "Nariño", orden: 10 },
    { codigo: null, valor: "Amazonas", orden: 20 },
    { codigo: null, valor: "Antioquia", orden: 30 },
    { codigo: null, valor: "Arauca", orden: 40 },
    { codigo: null, valor: "Atlántico", orden: 50 },
    { codigo: null, valor: "Bogotá D.C.", orden: 60 },
    { codigo: null, valor: "Bolívar", orden: 70 },
    { codigo: null, valor: "Boyacá", orden: 80 },
    { codigo: null, valor: "Caldas", orden: 90 },
    { codigo: null, valor: "Cali", orden: 100 },
    { codigo: null, valor: "Caquetá", orden: 110 },
    { codigo: null, valor: "Casanare", orden: 120 },
    { codigo: null, valor: "Cauca", orden: 130 },
    { codigo: null, valor: "Cesar", orden: 140 },
    { codigo: null, valor: "Chocó", orden: 150 },
    { codigo: null, valor: "Córdoba", orden: 160 },
    { codigo: null, valor: "Cundinamarca", orden: 170 },
    { codigo: null, valor: "Guainía", orden: 180 },
    { codigo: null, valor: "Guaviare", orden: 190 },
    { codigo: null, valor: "Huila", orden: 200 },
    { codigo: null, valor: "La Guajira", orden: 210 },
    { codigo: null, valor: "Magdalena", orden: 220 },
    { codigo: null, valor: "Meta", orden: 230 },
    { codigo: null, valor: "Norte de Santander", orden: 240 },
    { codigo: null, valor: "Putumayo", orden: 250 },
    { codigo: null, valor: "Quindío", orden: 260 },
    { codigo: null, valor: "Risaralda", orden: 270 },
    { codigo: null, valor: "San Andrés y Providencia", orden: 280 },
    { codigo: null, valor: "Santander", orden: 290 },
    { codigo: null, valor: "Sucre", orden: 300 },
    { codigo: null, valor: "Tolima", orden: 310 },
    { codigo: null, valor: "Valle del Cauca", orden: 320 },
    { codigo: null, valor: "Vaupés", orden: 330 },
    { codigo: null, valor: "Vichada", orden: 340 },
    { codigo: null, valor: "Ecuador", orden: 350 },
    { codigo: null, valor: "Otro país", orden: 360 },
  ],
  MUNICIPIOS: [
    { codigo: null, valor: "Pasto", orden: 10 },
    { codigo: null, valor: "Albán", orden: 20 },
    { codigo: null, valor: "Aldana", orden: 30 },
    { codigo: null, valor: "Ancuyá", orden: 40 },
    { codigo: null, valor: "Arboleda", orden: 50 },
    { codigo: null, valor: "Barbacoas", orden: 60 },
    { codigo: null, valor: "Belén", orden: 70 },
    { codigo: null, valor: "Buesaco", orden: 80 },
    { codigo: null, valor: "Chachagüí", orden: 90 },
    { codigo: null, valor: "Colón", orden: 100 },
    { codigo: null, valor: "Consacá", orden: 110 },
    { codigo: null, valor: "Contadero", orden: 120 },
    { codigo: null, valor: "Córdoba", orden: 130 },
    { codigo: null, valor: "Cuaspud", orden: 140 },
    { codigo: null, valor: "Cumbal", orden: 150 },
    { codigo: null, valor: "Cumbitara", orden: 160 },
    { codigo: null, valor: "El Charco", orden: 170 },
    { codigo: null, valor: "El Peñol", orden: 180 },
    { codigo: null, valor: "El Rosario", orden: 190 },
    { codigo: null, valor: "El Tablón de Gómez", orden: 200 },
    { codigo: null, valor: "El Tambo", orden: 210 },
    { codigo: null, valor: "Francisco Pizarro", orden: 220 },
    { codigo: null, valor: "Funes", orden: 230 },
    { codigo: null, valor: "Guachucal", orden: 240 },
    { codigo: null, valor: "Guaitarilla", orden: 250 },
    { codigo: null, valor: "Gualmatán", orden: 260 },
    { codigo: null, valor: "Iles", orden: 270 },
    { codigo: null, valor: "Imués", orden: 280 },
    { codigo: null, valor: "Ipiales", orden: 290 },
    { codigo: null, valor: "La Cruz", orden: 300 },
    { codigo: null, valor: "La Florida", orden: 310 },
    { codigo: null, valor: "La Llanada", orden: 320 },
    { codigo: null, valor: "La Tola", orden: 330 },
    { codigo: null, valor: "La Unión", orden: 340 },
    { codigo: null, valor: "Leiva", orden: 350 },
    { codigo: null, valor: "Linares", orden: 360 },
    { codigo: null, valor: "Los Andes", orden: 370 },
    { codigo: null, valor: "Magüí Payán", orden: 380 },
    { codigo: null, valor: "Mallama", orden: 390 },
    { codigo: null, valor: "Mosquera", orden: 400 },
    { codigo: null, valor: "Nariño", orden: 410 },
    { codigo: null, valor: "Olaya Herrera", orden: 420 },
    { codigo: null, valor: "Ospina", orden: 430 },
    { codigo: null, valor: "Policarpa", orden: 440 },
    { codigo: null, valor: "Potosí", orden: 450 },
    { codigo: null, valor: "Providencia", orden: 460 },
    { codigo: null, valor: "Puerres", orden: 470 },
    { codigo: null, valor: "Pupiales", orden: 480 },
    { codigo: null, valor: "Ricaurte", orden: 490 },
    { codigo: null, valor: "Roberto Payán", orden: 500 },
    { codigo: null, valor: "Samaniego", orden: 510 },
    { codigo: null, valor: "San Bernardo", orden: 520 },
    { codigo: null, valor: "San Lorenzo", orden: 530 },
    { codigo: null, valor: "San Pablo", orden: 540 },
    { codigo: null, valor: "San Pedro de Cartago", orden: 550 },
    { codigo: null, valor: "Sandoná", orden: 560 },
    { codigo: null, valor: "Santa Bárbara", orden: 570 },
    { codigo: null, valor: "Santacruz", orden: 580 },
    { codigo: null, valor: "Sapuyes", orden: 590 },
    { codigo: null, valor: "Taminango", orden: 600 },
    { codigo: null, valor: "Tangua", orden: 610 },
    { codigo: null, valor: "Tumaco", orden: 620 },
    { codigo: null, valor: "Túquerres", orden: 630 },
    { codigo: null, valor: "Yacuanquer", orden: 640 },
  ],
  EPS: [
    { codigo: null, valor: "AIC", orden: 10 },
    { codigo: null, valor: "Asmet Salud", orden: 20 },
    { codigo: null, valor: "Emssanar", orden: 30 },
    { codigo: null, valor: "Famisanar", orden: 40 },
    { codigo: null, valor: "Mallamas", orden: 50 },
    { codigo: null, valor: "Nueva EPS", orden: 60 },
    { codigo: null, valor: "Particular", orden: 70 },
    { codigo: null, valor: "Salud Total", orden: 80 },
    { codigo: null, valor: "Sanitas", orden: 90 },
    { codigo: null, valor: "SURA", orden: 100 },
    { codigo: null, valor: "Otra", orden: 110 },
  ],
  DIAGNOSTICO: [
    { codigo: null, valor: "Anomalía de Ebstein", orden: 10 },
    { codigo: null, valor: "Anomalías de las arterias coronarias", orden: 20 },
    { codigo: null, valor: "Anomalías de la aorta ascendente, arco o descendente (hipoplasia, estenosis, interrupción)", orden: 30 },
    { codigo: null, valor: "Atresia pulmonar", orden: 40 },
    { codigo: null, valor: "Atresia tricuspídea", orden: 50 },
    { codigo: null, valor: "Canal auriculoventricular", orden: 60 },
    { codigo: null, valor: "Coartación de aorta", orden: 70 },
    { codigo: null, valor: "Comunicación interauricular (CIA)", orden: 80 },
    { codigo: null, valor: "Comunicación interventricular (CIV)", orden: 90 },
    { codigo: null, valor: "Cuerpo extraño intracardíaco", orden: 100 },
    { codigo: null, valor: "Doble salida del ventrículo derecho", orden: 110 },
    { codigo: null, valor: "Drenaje anómalo de venas pulmonares", orden: 120 },
    { codigo: null, valor: "Estenosis aórtica / lesión obstructiva del tracto de salida izquierdo", orden: 130 },
    { codigo: null, valor: "Estenosis pulmonar", orden: 140 },
    { codigo: null, valor: "Persistencia del conducto arterioso (PCA)", orden: 150 },
    { codigo: null, valor: "Síndrome de corazón izquierdo hipoplásico", orden: 160 },
    { codigo: null, valor: "Tetralogía de Fallot", orden: 170 },
    { codigo: null, valor: "Transposición de grandes arterias", orden: 180 },
    { codigo: null, valor: "Tronco arterioso", orden: 190 },
    { codigo: 'VALVULOPATIAS', valor: "Valvulopatías", orden: 200 },
    { codigo: null, valor: "Ventana aortopulmonar", orden: 210 },
    { codigo: null, valor: "Ventrículo único / fisiología univentricular", orden: 220 },
    { codigo: null, valor: "Otras cardiopatías congénitas", orden: 230 },
  ],
  VALVULOPATIA: [
    { codigo: null, valor: "Estenosis", orden: 10 },
    { codigo: null, valor: "Insuficiencia", orden: 20 },
    { codigo: 'NA', valor: "N/A", orden: 30 },
  ],
  RIESGOS: [
    { codigo: null, valor: "Arritmias cardíacas", orden: 10 },
    { codigo: null, valor: "Cirugía cardíaca previa", orden: 20 },
    { codigo: null, valor: "Desnutrición", orden: 30 },
    { codigo: null, valor: "Disfunción ventricular", orden: 40 },
    { codigo: null, valor: "Endocarditis", orden: 50 },
    { codigo: null, valor: "Enfermedad renal", orden: 60 },
    { codigo: null, valor: "Hipertensión pulmonar", orden: 70 },
    { codigo: null, valor: "Infección activa", orden: 80 },
    { codigo: null, valor: "Insuficiencia cardíaca", orden: 90 },
    { codigo: null, valor: "Intervención previa por hemodinamia", orden: 100 },
    { codigo: null, valor: "Obesidad", orden: 110 },
    { codigo: null, valor: "Prematuridad / bajo peso al nacer", orden: 120 },
    { codigo: null, valor: "Síndrome genético (Down, Turner, DiGeorge, Noonan, Williams u otro)", orden: 130 },
    { codigo: null, valor: "Otra condición relevante", orden: 140 },
    { codigo: 'NINGUNO', valor: "Ninguno", orden: 150 },
  ],
  RACHS: [
    { codigo: null, valor: "I", orden: 10 },
    { codigo: null, valor: "II", orden: 20 },
    { codigo: null, valor: "III", orden: 30 },
    { codigo: null, valor: "IV", orden: 40 },
    { codigo: null, valor: "V", orden: 50 },
    { codigo: null, valor: "VI", orden: 60 },
  ],
  PROCEDIMIENTOS: [
    { codigo: null, valor: "Anastomosis cavopulmonar bidireccional (Glenn)", orden: 10 },
    { codigo: null, valor: "Bandaje de arteria pulmonar", orden: 20 },
    { codigo: null, valor: "Cierre de comunicación interauricular (CIA)", orden: 30 },
    { codigo: null, valor: "Cierre de comunicación interventricular (CIV)", orden: 40 },
    { codigo: null, valor: "Cierre de ductus arterioso persistente", orden: 50 },
    { codigo: null, valor: "Cirugía de aorta (ascendente, arco o descendente)", orden: 60 },
    { codigo: null, valor: "Cirugía de coartación de aorta", orden: 70 },
    { codigo: null, valor: "Corrección de canal auriculoventricular", orden: 80 },
    { codigo: null, valor: "Corrección de doble salida del ventrículo derecho", orden: 90 },
    { codigo: null, valor: "Corrección de drenaje venoso pulmonar anómalo", orden: 100 },
    { codigo: null, valor: "Corrección de tetralogía de Fallot", orden: 110 },
    { codigo: null, valor: "Corrección de transposición de grandes arterias / Switch arterial", orden: 120 },
    { codigo: null, valor: "Extracción de cuerpo extraño intracardíaco", orden: 130 },
    { codigo: null, valor: "Fístula sistémico-pulmonar", orden: 140 },
    { codigo: null, valor: "Procedimiento de Damus-Kaye-Stansel", orden: 150 },
    { codigo: null, valor: "Procedimiento de Fontan", orden: 160 },
    { codigo: null, valor: "Procedimiento de Norwood", orden: 170 },
    { codigo: null, valor: "Procedimiento de Rastelli", orden: 180 },
    { codigo: null, valor: "Reconstrucción de arteria pulmonar", orden: 190 },
    { codigo: null, valor: "Reemplazo valvular aórtico", orden: 200 },
    { codigo: null, valor: "Reemplazo valvular mitral", orden: 210 },
    { codigo: null, valor: "Reemplazo valvular pulmonar", orden: 220 },
    { codigo: null, valor: "Reemplazo valvular tricuspídeo", orden: 230 },
    { codigo: null, valor: "Reparación de anillos vasculares", orden: 240 },
    { codigo: null, valor: "Reparación de anomalía de Ebstein", orden: 250 },
    { codigo: null, valor: "Reparación de tronco arterioso", orden: 260 },
    { codigo: null, valor: "Reparación de ventana aortopulmonar", orden: 270 },
    { codigo: null, valor: "Resección de estenosis subaórtica", orden: 280 },
    { codigo: null, valor: "Valvuloplastia aórtica", orden: 290 },
    { codigo: null, valor: "Valvuloplastia mitral", orden: 300 },
    { codigo: null, valor: "Valvuloplastia pulmonar", orden: 310 },
    { codigo: null, valor: "Valvuloplastia tricuspídea", orden: 320 },
    { codigo: null, valor: "Otro", orden: 330 },
  ],
  IMPLANTE: [
    { codigo: null, valor: "Autólogo", orden: 10 },
    { codigo: null, valor: "Biológico", orden: 20 },
    { codigo: null, valor: "Mecánico", orden: 30 },
    { codigo: null, valor: "N/A", orden: 40 },
  ],
  COMPLICACION_INTRAQX: [
    { codigo: 'NINGUNA', valor: "Ninguna", orden: 10 },
    { codigo: null, valor: "Complicación de prótesis o injerto", orden: 20 },
    { codigo: null, valor: "Dehiscencia de sutura", orden: 30 },
    { codigo: null, valor: "Dificultad para finalizar la reparación quirúrgica", orden: 40 },
    { codigo: null, valor: "Disección aórtica intraoperatoria", orden: 50 },
    { codigo: null, valor: "Falla de reparación quirúrgica", orden: 60 },
    { codigo: null, valor: "Fuga paravalvular", orden: 70 },
    { codigo: null, valor: "Hemorragia quirúrgica significativa", orden: 80 },
    { codigo: null, valor: "Lesión cardíaca o vascular", orden: 90 },
    { codigo: null, valor: "Muerte intraoperatoria", orden: 100 },
    { codigo: null, valor: "Necesidad de soporte circulatorio mecánico (ECMO)", orden: 110 },
    { codigo: null, valor: "Reintervención durante el mismo acto quirúrgico", orden: 120 },
    { codigo: null, valor: "Otra", orden: 130 },
  ],
  UNIDAD_POP: [
    { codigo: null, valor: "UCI Pediátrica", orden: 10 },
    { codigo: null, valor: "UCI Neonatos", orden: 20 },
    { codigo: null, valor: "UCI Adultos", orden: 30 },
    { codigo: null, valor: "N/A", orden: 40 },
  ],
  COMPLICACION_POP: [
    { codigo: 'NO', valor: "No", orden: 10 },
    { codigo: null, valor: "ACV postoperatorio", orden: 20 },
    { codigo: null, valor: "ECMO", orden: 30 },
    { codigo: null, valor: "Falla renal POP que requiera diálisis", orden: 40 },
    { codigo: null, valor: "Fibrilación auricular postoperatoria", orden: 50 },
    { codigo: null, valor: "Implante de marcapaso definitivo por bloqueo AV", orden: 60 },
    { codigo: null, valor: "Infarto perioperatorio", orden: 70 },
    { codigo: null, valor: "Intubación prolongada mayor a 72 horas", orden: 80 },
    { codigo: null, valor: "Mediastinitis", orden: 90 },
    { codigo: 'MUERTE', valor: "Muerte", orden: 100 },
    { codigo: null, valor: "Reingreso a UCI", orden: 110 },
    { codigo: null, valor: "Reintervención por otra causa diferente a sangrado", orden: 120 },
    { codigo: null, valor: "Reintervención por sangrado", orden: 130 },
    { codigo: null, valor: "Reintubación", orden: 140 },
    { codigo: null, valor: "Sangrado significativo", orden: 150 },
    { codigo: null, valor: "Shock cardiogénico", orden: 160 },
    { codigo: null, valor: "Otra", orden: 170 },
  ],
  CONDICION_SALIDA: [
    { codigo: null, valor: "Estable", orden: 10 },
    { codigo: null, valor: "Estable con oxígeno domiciliario", orden: 20 },
    { codigo: null, valor: "Remitido", orden: 30 },
    { codigo: null, valor: "Alta voluntaria", orden: 40 },
    { codigo: 'MUERTE', valor: "Muerte", orden: 50 },
    { codigo: null, valor: "Otro", orden: 60 },
  ],
  ESTADO_HERIDA: [
    { codigo: null, valor: "Cicatrización adecuada", orden: 10 },
    { codigo: null, valor: "Dehiscencia", orden: 20 },
    { codigo: null, valor: "Eritema", orden: 30 },
    { codigo: null, valor: "Hematoma", orden: 40 },
    { codigo: null, valor: "Infección", orden: 50 },
    { codigo: null, valor: "Necrosis", orden: 60 },
    { codigo: null, valor: "Sangrado", orden: 70 },
    { codigo: null, valor: "Secreción", orden: 80 },
    { codigo: null, valor: "Seroma", orden: 90 },
    { codigo: null, valor: "Otro", orden: 100 },
    { codigo: null, valor: "N/A", orden: 110 },
  ],
  CAUSA_REINGRESO: [
    { codigo: null, valor: "N/A", orden: 10 },
    { codigo: null, valor: "Arritmia", orden: 20 },
    { codigo: null, valor: "Complicación de prótesis o injerto", orden: 30 },
    { codigo: null, valor: "Complicación renal", orden: 40 },
    { codigo: null, valor: "Complicación respiratoria", orden: 50 },
    { codigo: null, valor: "Dehiscencia de herida quirúrgica", orden: 60 },
    { codigo: null, valor: "Derrame pericárdico", orden: 70 },
    { codigo: null, valor: "Derrame pleural", orden: 80 },
    { codigo: null, valor: "Disfunción valvular", orden: 90 },
    { codigo: null, valor: "Embolia", orden: 100 },
    { codigo: null, valor: "Infección de herida quirúrgica", orden: 110 },
    { codigo: null, valor: "Insuficiencia cardíaca", orden: 120 },
    { codigo: null, valor: "Sangrado", orden: 130 },
    { codigo: null, valor: "Síndrome de bajo gasto cardíaco", orden: 140 },
    { codigo: null, valor: "Taponamiento cardíaco", orden: 150 },
    { codigo: null, valor: "Trombosis", orden: 160 },
    { codigo: null, valor: "Otra complicación cardiovascular", orden: 170 },
    { codigo: null, valor: "Otra causa no cardiovascular", orden: 180 },
  ],
}
